// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dex/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgLimitBuy struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Price    int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity int32  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (m *MsgLimitBuy) Reset()         { *m = MsgLimitBuy{} }
func (m *MsgLimitBuy) String() string { return proto.CompactTextString(m) }
func (*MsgLimitBuy) ProtoMessage()    {}
func (*MsgLimitBuy) Descriptor() ([]byte, []int) {
	return fileDescriptor_463701e671e5a5e0, []int{0}
}
func (m *MsgLimitBuy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLimitBuy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLimitBuy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLimitBuy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLimitBuy.Merge(m, src)
}
func (m *MsgLimitBuy) XXX_Size() int {
	return m.Size()
}
func (m *MsgLimitBuy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLimitBuy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLimitBuy proto.InternalMessageInfo

func (m *MsgLimitBuy) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgLimitBuy) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MsgLimitBuy) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type MsgLimitBuyResponse struct {
}

func (m *MsgLimitBuyResponse) Reset()         { *m = MsgLimitBuyResponse{} }
func (m *MsgLimitBuyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLimitBuyResponse) ProtoMessage()    {}
func (*MsgLimitBuyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_463701e671e5a5e0, []int{1}
}
func (m *MsgLimitBuyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLimitBuyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLimitBuyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLimitBuyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLimitBuyResponse.Merge(m, src)
}
func (m *MsgLimitBuyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLimitBuyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLimitBuyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLimitBuyResponse proto.InternalMessageInfo

type MsgLimitSell struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Price    int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity int32  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (m *MsgLimitSell) Reset()         { *m = MsgLimitSell{} }
func (m *MsgLimitSell) String() string { return proto.CompactTextString(m) }
func (*MsgLimitSell) ProtoMessage()    {}
func (*MsgLimitSell) Descriptor() ([]byte, []int) {
	return fileDescriptor_463701e671e5a5e0, []int{2}
}
func (m *MsgLimitSell) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLimitSell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLimitSell.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLimitSell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLimitSell.Merge(m, src)
}
func (m *MsgLimitSell) XXX_Size() int {
	return m.Size()
}
func (m *MsgLimitSell) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLimitSell.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLimitSell proto.InternalMessageInfo

func (m *MsgLimitSell) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgLimitSell) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MsgLimitSell) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type MsgLimitSellResponse struct {
}

func (m *MsgLimitSellResponse) Reset()         { *m = MsgLimitSellResponse{} }
func (m *MsgLimitSellResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLimitSellResponse) ProtoMessage()    {}
func (*MsgLimitSellResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_463701e671e5a5e0, []int{3}
}
func (m *MsgLimitSellResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLimitSellResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLimitSellResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLimitSellResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLimitSellResponse.Merge(m, src)
}
func (m *MsgLimitSellResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLimitSellResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLimitSellResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLimitSellResponse proto.InternalMessageInfo

type MsgMarketBuy struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (m *MsgMarketBuy) Reset()         { *m = MsgMarketBuy{} }
func (m *MsgMarketBuy) String() string { return proto.CompactTextString(m) }
func (*MsgMarketBuy) ProtoMessage()    {}
func (*MsgMarketBuy) Descriptor() ([]byte, []int) {
	return fileDescriptor_463701e671e5a5e0, []int{4}
}
func (m *MsgMarketBuy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMarketBuy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMarketBuy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMarketBuy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMarketBuy.Merge(m, src)
}
func (m *MsgMarketBuy) XXX_Size() int {
	return m.Size()
}
func (m *MsgMarketBuy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMarketBuy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMarketBuy proto.InternalMessageInfo

func (m *MsgMarketBuy) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgMarketBuy) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type MsgMarketBuyResponse struct {
}

func (m *MsgMarketBuyResponse) Reset()         { *m = MsgMarketBuyResponse{} }
func (m *MsgMarketBuyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMarketBuyResponse) ProtoMessage()    {}
func (*MsgMarketBuyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_463701e671e5a5e0, []int{5}
}
func (m *MsgMarketBuyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMarketBuyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMarketBuyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMarketBuyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMarketBuyResponse.Merge(m, src)
}
func (m *MsgMarketBuyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMarketBuyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMarketBuyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMarketBuyResponse proto.InternalMessageInfo

type MsgMarketSell struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (m *MsgMarketSell) Reset()         { *m = MsgMarketSell{} }
func (m *MsgMarketSell) String() string { return proto.CompactTextString(m) }
func (*MsgMarketSell) ProtoMessage()    {}
func (*MsgMarketSell) Descriptor() ([]byte, []int) {
	return fileDescriptor_463701e671e5a5e0, []int{6}
}
func (m *MsgMarketSell) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMarketSell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMarketSell.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMarketSell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMarketSell.Merge(m, src)
}
func (m *MsgMarketSell) XXX_Size() int {
	return m.Size()
}
func (m *MsgMarketSell) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMarketSell.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMarketSell proto.InternalMessageInfo

func (m *MsgMarketSell) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgMarketSell) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type MsgMarketSellResponse struct {
}

func (m *MsgMarketSellResponse) Reset()         { *m = MsgMarketSellResponse{} }
func (m *MsgMarketSellResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMarketSellResponse) ProtoMessage()    {}
func (*MsgMarketSellResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_463701e671e5a5e0, []int{7}
}
func (m *MsgMarketSellResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMarketSellResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMarketSellResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMarketSellResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMarketSellResponse.Merge(m, src)
}
func (m *MsgMarketSellResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMarketSellResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMarketSellResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMarketSellResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgLimitBuy)(nil), "codchen.newchainpoc.dex.MsgLimitBuy")
	proto.RegisterType((*MsgLimitBuyResponse)(nil), "codchen.newchainpoc.dex.MsgLimitBuyResponse")
	proto.RegisterType((*MsgLimitSell)(nil), "codchen.newchainpoc.dex.MsgLimitSell")
	proto.RegisterType((*MsgLimitSellResponse)(nil), "codchen.newchainpoc.dex.MsgLimitSellResponse")
	proto.RegisterType((*MsgMarketBuy)(nil), "codchen.newchainpoc.dex.MsgMarketBuy")
	proto.RegisterType((*MsgMarketBuyResponse)(nil), "codchen.newchainpoc.dex.MsgMarketBuyResponse")
	proto.RegisterType((*MsgMarketSell)(nil), "codchen.newchainpoc.dex.MsgMarketSell")
	proto.RegisterType((*MsgMarketSellResponse)(nil), "codchen.newchainpoc.dex.MsgMarketSellResponse")
}

func init() { proto.RegisterFile("dex/tx.proto", fileDescriptor_463701e671e5a5e0) }

var fileDescriptor_463701e671e5a5e0 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xb1, 0x4e, 0xc2, 0x40,
	0x18, 0xc7, 0x29, 0x04, 0x85, 0x4f, 0x5c, 0x4e, 0x90, 0x86, 0xa1, 0x21, 0x44, 0x0d, 0x03, 0x5c,
	0x13, 0x7d, 0x03, 0xa2, 0x4e, 0xb2, 0xe0, 0x24, 0x83, 0x49, 0xb9, 0x7e, 0x81, 0x46, 0xe8, 0xd5,
	0xf6, 0x08, 0xe5, 0x2d, 0xf4, 0xad, 0x1c, 0x19, 0x1d, 0x0d, 0xbc, 0x88, 0xf1, 0xb4, 0xc7, 0x19,
	0x95, 0x76, 0x70, 0xfc, 0xae, 0xff, 0xfb, 0xfd, 0xf2, 0xf5, 0x9f, 0x83, 0x8a, 0x8b, 0xb1, 0x2d,
	0x62, 0x1a, 0x84, 0x5c, 0x70, 0x52, 0x67, 0xdc, 0x65, 0x13, 0xf4, 0xa9, 0x8f, 0x0b, 0x36, 0x71,
	0x3c, 0x3f, 0xe0, 0x8c, 0xba, 0x18, 0xb7, 0xee, 0xe0, 0xa0, 0x1f, 0x8d, 0x6f, 0xbc, 0x99, 0x27,
	0x7a, 0xf3, 0x25, 0x31, 0x61, 0x9f, 0x85, 0xe8, 0x08, 0x1e, 0x9a, 0x46, 0xd3, 0x68, 0x97, 0x07,
	0xc9, 0x48, 0xaa, 0x50, 0x0c, 0x42, 0x8f, 0xa1, 0x99, 0x6f, 0x1a, 0xed, 0xe2, 0xe0, 0x73, 0x20,
	0x0d, 0x28, 0x3d, 0xce, 0x1d, 0x5f, 0x78, 0x62, 0x69, 0x16, 0xe4, 0x07, 0x35, 0xb7, 0x6a, 0x70,
	0xa4, 0xa1, 0x07, 0x18, 0x05, 0xdc, 0x8f, 0xb0, 0x35, 0x84, 0x4a, 0x72, 0x7c, 0x8b, 0xd3, 0xe9,
	0xbf, 0x2a, 0x8f, 0xa1, 0xaa, 0xb3, 0x95, 0xf3, 0x52, 0x3a, 0xfb, 0x4e, 0xf8, 0x80, 0x29, 0x6b,
	0xea, 0xf4, 0xfc, 0xaf, 0x74, 0x45, 0x51, 0xf4, 0x2b, 0x38, 0x54, 0xe7, 0x29, 0x2b, 0xed, 0xc2,
	0xd7, 0xa1, 0xf6, 0x0d, 0x93, 0xf0, 0xcf, 0x9f, 0x0b, 0x50, 0xe8, 0x47, 0x63, 0x72, 0x0f, 0x25,
	0x55, 0xd4, 0x09, 0xfd, 0xa3, 0x51, 0xaa, 0xfd, 0xf3, 0x46, 0x27, 0x4b, 0x2a, 0xf1, 0x10, 0x07,
	0xca, 0xdb, 0x5a, 0x4e, 0x53, 0xaf, 0x7e, 0xc4, 0x1a, 0xdd, 0x4c, 0x31, 0x5d, 0xb1, 0x6d, 0x61,
	0xa7, 0x42, 0xc5, 0x76, 0x2b, 0x7e, 0xb4, 0x41, 0x5c, 0x00, 0xad, 0x8a, 0xb3, 0xf4, 0xcb, 0x72,
	0x0f, 0x9a, 0x2d, 0x97, 0x58, 0x7a, 0xd7, 0x2f, 0x6b, 0xcb, 0x58, 0xad, 0x2d, 0xe3, 0x6d, 0x6d,
	0x19, 0x4f, 0x1b, 0x2b, 0xb7, 0xda, 0x58, 0xb9, 0xd7, 0x8d, 0x95, 0x1b, 0x76, 0xc6, 0x9e, 0x98,
	0xcc, 0x47, 0x94, 0xf1, 0x99, 0xfd, 0xc5, 0xb4, 0x7d, 0x5c, 0x74, 0x25, 0xb4, 0x1b, 0x70, 0x66,
	0xc7, 0xb6, 0x7c, 0x9b, 0xcb, 0x00, 0xa3, 0xd1, 0x9e, 0x7c, 0x9f, 0x17, 0xef, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xff, 0x68, 0x39, 0xc7, 0xaf, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	LimitBuy(ctx context.Context, in *MsgLimitBuy, opts ...grpc.CallOption) (*MsgLimitBuyResponse, error)
	LimitSell(ctx context.Context, in *MsgLimitSell, opts ...grpc.CallOption) (*MsgLimitSellResponse, error)
	MarketBuy(ctx context.Context, in *MsgMarketBuy, opts ...grpc.CallOption) (*MsgMarketBuyResponse, error)
	MarketSell(ctx context.Context, in *MsgMarketSell, opts ...grpc.CallOption) (*MsgMarketSellResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) LimitBuy(ctx context.Context, in *MsgLimitBuy, opts ...grpc.CallOption) (*MsgLimitBuyResponse, error) {
	out := new(MsgLimitBuyResponse)
	err := c.cc.Invoke(ctx, "/codchen.newchainpoc.dex.Msg/LimitBuy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) LimitSell(ctx context.Context, in *MsgLimitSell, opts ...grpc.CallOption) (*MsgLimitSellResponse, error) {
	out := new(MsgLimitSellResponse)
	err := c.cc.Invoke(ctx, "/codchen.newchainpoc.dex.Msg/LimitSell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MarketBuy(ctx context.Context, in *MsgMarketBuy, opts ...grpc.CallOption) (*MsgMarketBuyResponse, error) {
	out := new(MsgMarketBuyResponse)
	err := c.cc.Invoke(ctx, "/codchen.newchainpoc.dex.Msg/MarketBuy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MarketSell(ctx context.Context, in *MsgMarketSell, opts ...grpc.CallOption) (*MsgMarketSellResponse, error) {
	out := new(MsgMarketSellResponse)
	err := c.cc.Invoke(ctx, "/codchen.newchainpoc.dex.Msg/MarketSell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	LimitBuy(context.Context, *MsgLimitBuy) (*MsgLimitBuyResponse, error)
	LimitSell(context.Context, *MsgLimitSell) (*MsgLimitSellResponse, error)
	MarketBuy(context.Context, *MsgMarketBuy) (*MsgMarketBuyResponse, error)
	MarketSell(context.Context, *MsgMarketSell) (*MsgMarketSellResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) LimitBuy(ctx context.Context, req *MsgLimitBuy) (*MsgLimitBuyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LimitBuy not implemented")
}
func (*UnimplementedMsgServer) LimitSell(ctx context.Context, req *MsgLimitSell) (*MsgLimitSellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LimitSell not implemented")
}
func (*UnimplementedMsgServer) MarketBuy(ctx context.Context, req *MsgMarketBuy) (*MsgMarketBuyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarketBuy not implemented")
}
func (*UnimplementedMsgServer) MarketSell(ctx context.Context, req *MsgMarketSell) (*MsgMarketSellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarketSell not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_LimitBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLimitBuy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LimitBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codchen.newchainpoc.dex.Msg/LimitBuy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LimitBuy(ctx, req.(*MsgLimitBuy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_LimitSell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLimitSell)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LimitSell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codchen.newchainpoc.dex.Msg/LimitSell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LimitSell(ctx, req.(*MsgLimitSell))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MarketBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMarketBuy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MarketBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codchen.newchainpoc.dex.Msg/MarketBuy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MarketBuy(ctx, req.(*MsgMarketBuy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MarketSell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMarketSell)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MarketSell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codchen.newchainpoc.dex.Msg/MarketSell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MarketSell(ctx, req.(*MsgMarketSell))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "codchen.newchainpoc.dex.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LimitBuy",
			Handler:    _Msg_LimitBuy_Handler,
		},
		{
			MethodName: "LimitSell",
			Handler:    _Msg_LimitSell_Handler,
		},
		{
			MethodName: "MarketBuy",
			Handler:    _Msg_MarketBuy_Handler,
		},
		{
			MethodName: "MarketSell",
			Handler:    _Msg_MarketSell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dex/tx.proto",
}

func (m *MsgLimitBuy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLimitBuy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLimitBuy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Quantity != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Quantity))
		i--
		dAtA[i] = 0x18
	}
	if m.Price != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLimitBuyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLimitBuyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLimitBuyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgLimitSell) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLimitSell) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLimitSell) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Quantity != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Quantity))
		i--
		dAtA[i] = 0x18
	}
	if m.Price != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLimitSellResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLimitSellResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLimitSellResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgMarketBuy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMarketBuy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMarketBuy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Quantity != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Quantity))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMarketBuyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMarketBuyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMarketBuyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgMarketSell) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMarketSell) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMarketSell) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Quantity != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Quantity))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMarketSellResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMarketSellResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMarketSellResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgLimitBuy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Price != 0 {
		n += 1 + sovTx(uint64(m.Price))
	}
	if m.Quantity != 0 {
		n += 1 + sovTx(uint64(m.Quantity))
	}
	return n
}

func (m *MsgLimitBuyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgLimitSell) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Price != 0 {
		n += 1 + sovTx(uint64(m.Price))
	}
	if m.Quantity != 0 {
		n += 1 + sovTx(uint64(m.Quantity))
	}
	return n
}

func (m *MsgLimitSellResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgMarketBuy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Quantity != 0 {
		n += 1 + sovTx(uint64(m.Quantity))
	}
	return n
}

func (m *MsgMarketBuyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgMarketSell) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Quantity != 0 {
		n += 1 + sovTx(uint64(m.Quantity))
	}
	return n
}

func (m *MsgMarketSellResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgLimitBuy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLimitBuy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLimitBuy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			m.Quantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quantity |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLimitBuyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLimitBuyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLimitBuyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLimitSell) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLimitSell: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLimitSell: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			m.Quantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quantity |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLimitSellResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLimitSellResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLimitSellResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMarketBuy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMarketBuy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMarketBuy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			m.Quantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quantity |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMarketBuyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMarketBuyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMarketBuyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMarketSell) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMarketSell: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMarketSell: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			m.Quantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quantity |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMarketSellResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMarketSellResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMarketSellResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
